#PBS -P jq14
#PBS -q normal
#PBS -l walltime=1:00:00
#PBS -l mem=1000GB
#PBS -l jobfs=10MB
#PBS -l ncpus=12
#PBS -l software=underworld
#PBS -l wd
#PBS -l storage=scratch/jq14
#PBS -N Model

source /scratch/jq14/lp5029/CODES/UWGeodynamics_2.9.10.sh

MODELNAME="Model_Name"
OUTPUTPATH=`pwd`
SCRIPT="model_script.py"

# execution
mpiexec python3 ./$SCRIPT 1> $OUTPUTPATH/$MODELNAME.$PBS_JOBID.log 2> $OUTPUTPATH/$MODELNAME.$PBS_JOBID.err
